#!/bin/bash

echo -e "
Starting Python Web Server
"


read -e -p "Select the directory to place scan results ($PWD): " SELECTED_FOLDER && [  -z "$SELECTED_FOLDER" ] && SELECTED_FOLDER=$PWD 
read -p "Select the server port: (9000): " SELECTED_PORT && [ -z "$SELECTED_PORT" ] && SELECTED_PORT=9000

python3 -m http.server $SELECTED_PORT --directory $SELECTED_FOLDER
